/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Enrollment;

import Information.Parent;
import Information.Student;
import Information.StudentGuardian;
import LoginSystem.Login;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
/**
 *
 * @author PC
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public static Dashboard dashboard;

    private static ArrayList<String> studentName;
    private static ArrayList<Integer> studentDetails;
    private static ArrayList<Integer> studentContactDetails;
    private static ArrayList<Integer> guardianDetails;
    private static ArrayList<String> parentName;
    private static ArrayList<Integer> parentDetails;


    public Dashboard() {
        initComponents();
        studentName = new ArrayList<>();
        studentDetails = new ArrayList<>();
        studentContactDetails = new ArrayList<>();
        parentName = new ArrayList<>();       
        parentDetails = new ArrayList<>();
        guardianDetails = new ArrayList<>();
    }

    protected static void setTab(int number) {
        jTabbedPane1.setSelectedIndex(number);
    }

    protected static void close() {
        Student student = new Student(studentName.get(0), studentName.get(1), studentName.get(2),
                studentContactDetails.get(0), studentDetails.get(0), studentDetails.get(1));
        Parent parent1 = new Parent(parentName.get(0), parentDetails.get(0), student.getStudentID());
        parent1.printParent();
        Parent parent2 = new Parent(parentName.get(1), parentDetails.get(1), student.getStudentID());
        parent2.printParent();
        StudentGuardian studentGuardian = new StudentGuardian(guardianDetails.get(0), student.getStudentID());
        JOptionPane.showMessageDialog(null, "Success");
        System.exit(0);
    }

    protected static void setStudentDetails(String firstName, String middleName, String lastName,
            int user_ID, int Class_Program_ID) {

        studentName.add(firstName);
        studentName.add(middleName);
        studentName.add(lastName);
        studentDetails.add(user_ID);
        studentDetails.add(Class_Program_ID);

    }

    protected static void setParentDetails(String name, int contact_Info_ID) {
        parentName.add(name);
        parentDetails.add(contact_Info_ID);
        

    }

    protected static void setStudentContactDetails(int address_ID, int contact_Info_ID) {
        studentContactDetails.add(address_ID);
        studentContactDetails.add(contact_Info_ID);

    }

    protected static void setStudentGuardian(int guardian_ID) {
        guardianDetails.add(guardian_ID);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guardianContactDetails1 = new Enrollment.GuardianContactDetails();
        guardianContactDetails2 = new Enrollment.GuardianContactDetails();
        contactDetails2 = new Enrollment.ContactDetails();
        guardianContactDetails3 = new Enrollment.GuardianContactDetails();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        newJPanel1 = new Enrollment.NewJPanel();
        studentDetails1 = new Enrollment.StudentDetails();
        contactDetails1 = new Enrollment.ContactDetails();
        guardianContactDetails4 = new Enrollment.GuardianContactDetails();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(1080, 800));
        jLayeredPane1.setRequestFocusEnabled(false);

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1080, 800));

        javax.swing.GroupLayout newJPanel1Layout = new javax.swing.GroupLayout(newJPanel1);
        newJPanel1.setLayout(newJPanel1Layout);
        newJPanel1Layout.setHorizontalGroup(
            newJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        newJPanel1Layout.setVerticalGroup(
            newJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 769, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab1", newJPanel1);
        jTabbedPane1.addTab("tab2", studentDetails1);
        jTabbedPane1.addTab("tab3", contactDetails1);
        jTabbedPane1.addTab("tab4", guardianContactDetails4);

        jLayeredPane1.setLayer(jTabbedPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        new Login().setVisible(true);
    }// GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dashboard = new Dashboard();
                dashboard.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Enrollment.ContactDetails contactDetails1;
    private Enrollment.ContactDetails contactDetails2;
    private Enrollment.GuardianContactDetails guardianContactDetails1;
    private Enrollment.GuardianContactDetails guardianContactDetails2;
    private Enrollment.GuardianContactDetails guardianContactDetails3;
    private Enrollment.GuardianContactDetails guardianContactDetails4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private static javax.swing.JTabbedPane jTabbedPane1;
    private Enrollment.NewJPanel newJPanel1;
    private Enrollment.StudentDetails studentDetails1;
    // End of variables declaration//GEN-END:variables
}
